# Write a function to compute 5/0 and use try/except to catch the exceptions

def fun():
    
    try:
        x = 5/0
    except:
        print("It is an error")

fun()